### PR TITLE
Nc news error handling

### PR DESCRIPTION
**Pull request by brunoFernandes21**

### CODE REVIEW

**Review by mezzDavies — CHANGES_REQUESTED** [review]
This is close - I am getting some of the errors but some functionality isn't there to be able to test others. For example I should see an appropriate error if going to a path for a non-existent topic (404) eg `topics/strawberries`. Currently though your url doesn't reflect the topic in this way (it mimics the api query instead). Please have a look into that and then you can add the appropriate error. 

Also, when I click to view the comments for an article I get a blank page at the moment. Perhaps have a quick play around with your app to check all the functionality is still working as you'd hope. It deserves to work properly as this is a nice looking app that I can tell you have worked hard to produce 👍 

Just in case you've seen there is also little trouble with some images:
image

**Comment by brunoFernandes21** [comment]
When I click to see the comments for an article, all of the comments come up on a list. So I don't understand why you would see a blank page. 
I will fix the pictures later one, as I am focusing on the functionality at the moment. 
Isn't the topic url supposed to be /articles?topic="topic" as it is a query?

**Review by mezzDavies — APPROVED** [review]
Approved 👍

**Comment by brunoFernandes21** [comment]
Thanks, Mezz. Much appreciated!

**Pull request merged**
